### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by gri38** [marph91/joppy#20]
Hello. 
This is not really an issue, more a disussion.

As you know I'm using your super API for Joplin.
I'm currently using 0.0.5, and I would like to update, but I don't know what the new releases bring and if ot worth the time. And if it remains compatible (I guess yes since no major version update?).

Could you explain your versionning logic: is X.Y.Z: X major = compatibility, and Y = new endpoints?

A changelog at the project root may help about that.

**Comment by marph91** [comment]
Hi, thanks for the kind words :)

Until now, nobody requested a changelog, so I didn't take the time to create it. But maybe now is the time to add it, since some people are using joppy.

> Could you explain your versionning logic: is X.Y.Z: X major = compatibility, and Y = new endpoints?

TBH I just incremented the versions by feel, but keeping major version 0 to denote it as beta. It might be reasonable to start with a 1.0.0 and keep a clear logic, but I can't promise when I will have time for this (and the changelog).

> And if it remains compatible (I guess yes since no major version update?).

To answer at least this question: The update to 0.1.0 would probably break things. The returned objects are no longer dicts, but dataclasses (see #17). Some code would have to be changed, but it should be mostly simple refactoring (as in the PR).
